# Generated by Django 3.2.20 on 2023-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_discount',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
