# Generated by Django 3.2.20 on 2023-11-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
        ('discount', '0002_alter_book_discount_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_discount',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book_discount',
            name='title',
        ),
        migrations.AddField(
            model_name='book_discount',
            name='auth_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='books_type',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='stock',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='book_discount',
            name='year',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
