# Generated by Django 3.2.20 on 2023-09-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
